#Chapter 4 
##NumPy

Rachel is very happy with the way you cleaned and structured the employee data last time, but she wants to take things one step further. The sales team wants to track the performance of the employees not only by the revenue they generated, but also taking the number of calls and the average deal size into account. For that, Rachel wants you to create a software for reporting. To be able to perform calculations on the data you decide that creating a data structure using Numpy will be best.

### Get the data

First, you need to get the data. You created lists with the relevant information in the last chapter.

📌 Copy and paste the lists "names", "call_numbers", "average_deal_size", and "revenues" you created in chapter 3 and assign them to variables.

In [169]:
# Taking file to not write lists by hand. Give basic tasks to program to do it for you.
file = open("employee_revenue.txt", "r")
data = file.read()
lines = data.splitlines()

# Created lists to use.
names_list = []
call_numbers_list = []
average_deal_size_list = []
revenues_list = []


In [170]:
# Use the clean_extract function from guided project 3 to fill the lists.
def clean_extract(lines, names, calls, average_deal_sizes, revenues):
    for employee in lines:
        employee = employee.strip(" ")
        employee = employee.lower()
        employee = employee.capitalize()
        
        split_employee = employee.split()
        split_employee[0] = split_employee[0].replace(",", "")
        names.append(split_employee[0])
        calls.append(int(split_employee[2]))
        
        for i in split_employee:
            if "$" in i:
                average_deal_size = i
                average_deal_size = average_deal_size.split("$")[0]
                average_deal_sizes.append(int(average_deal_size))
        
        dollars_index = split_employee.index("dollars")
        revenues.append(int(split_employee[dollars_index-1]))
    
    return names, calls, average_deal_sizes, revenues

In [171]:
# Calling the function and fill the lists.
names_list, calls_list, average_deal_size_list, revenue_list = clean_extract(lines, names_list, call_numbers_list, average_deal_size_list, revenues_list)

### Importing NumPy

You plan to create a data structure using NumPy.

📌 Import the NumPy library as.

In [172]:
#Import the NumPy library
import numpy as np

###Creating an initial (base) arrays

Next, you need to prepare an array in which you will store the values. The initial array will be empty. Since it will hold numerical data, the data type should be integer.

📌 Create an empty array using .array(). 

📌 Use the *dtype* parameter to specify the data type.

In [173]:
#Create an empty array with the data type integer
data = np.array([], dtype=int)

###Functions to add the data

Now that your empty array is ready, you need to transfer the data from the lists to the array. You create 2 functions functions for this. 

1. append_names function: A function that takes the "names" list and adds the index of each name to the "data" array.

  📌 Use a for loop and the .append() method for the indexes.

2. append_performance_measures function: A function that takes one of the remaining lists to add the sales performance data like number of calls, average deal size and revenue to the "data" array.

  📌 Use the .append() method.

In [174]:
#Define the append_names function
def append_names(list_name, array_name):
    for i in list_name:
        array_name = np.append(array_name, list_name.index(i))
    return array_name

In [175]:
#Define the append_performance_measures function
def append_performance_measures(list_name, array_name):
    array_name = np.append(array_name, list_name)
    return array_name

Call the functions to add the data to the array and print the array and its shape to see the result.

📌 Use the .shape() method.

In [176]:
#Use the append_names and append_sales_performance_measures to add the data
data = append_names(names_list, data)
data = append_performance_measures(call_numbers_list, data)
data = append_performance_measures(average_deal_size_list, data)
data = append_performance_measures(revenues_list, data)

#Print the array and its shape to see the result
print(f"Shape of the data array: {data.shape}")
print(f"Size of the data array: {data.size}")


Shape of the data array: (44,)
Size of the data array: 44


###Reshape the array

But like this, your array is not very structured. You need a 2D-array to be able to work better with it. The original data was 4 lists each with 11 values. So, the "data" array should have 4 rows and 11 columns. Print the result afterwards.

📌 Use the .reshape() method to rearrange the values in the array.


In [177]:
#Use the .reshape() method to change the array structure to 4 rows and 11 columns
data = data.reshape(4,11)

#Print the resulting array and its shape
print(f"Data array: {data}")
print(f"Shape and size of the data array: {data.shape} and {data.size}")

Data array: [[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]]
Shape and size of the data array: (4, 11) and 44


###Accessing values

Inside the array you can access the values in different ways. 

1. Print each row separately. 

  📌 Write down the array name and the index of the row you want to access.


In [178]:
#Print the name indexes
print(f"First row (names indexes): {data[0]}")

First row (names indexes): [ 0  1  2  3  4  5  6  7  8  9 10]


In [179]:
#Print the number of calls
print(f"Second row (call_numbers): {data[1]}")

Second row (call_numbers): [300  10 500  70 100 100 600 800 200 450  80]


In [180]:
#Print the average deal sizes
print(f"Third row (average deal sizes): {data[2]}")

Third row (average deal sizes): [ 8  6 24 32  5 25 25 40 15 10 12]


In [181]:
#Print the revenues 
print(f"Fourth row (revenues): {data[3]}")

Fourth row (revenues): [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]


2. Print a specific value.

  📌 Give the index of the row and the column of the value you want to access.
  For example, to get the revenue generated by Ellen, specify the value in the 3rd row and 7th column.

In [182]:
#Print the revenue generated by entered user.
employee_name = input("Enter the employee name:")
name_index = names_list.index(employee_name)
print(f"{employee_name} generated {data[3][name_index]} revenue for the company.")

Ellen generated 6000 revenue for the company.


###Analyzing the data

Great, your array is ready!

The sales team has a formula that they use to calculate the performance score of an employee.


\begin{align}
        \text{Performance} = \frac{\text{Average deal size x Revenue}}{\text{Number of calls}}
    \end{align}


📌 Create a function called “calculate_performance” to implement this formula. It should take the employee name as an input.

In [183]:
#Define the function calculate_performance
def calculate_performance(array_name, name_list, employee_name):
    name_index = name_list.index(employee_name)
    performance = (array_name[2][name_index]*array_name[3][name_index])/array_name[1][name_index]
    return performance
    

###Try it out

Let's check Ellen's performance score and print the result.

In [184]:
#Use the calculate performance function to print Ellen's performance
employee_name_entry = input("Enter the employee name:")
employee_performance = calculate_performance(data, names_list, employee_name_entry)

print(f"{employee_name_entry}'s performance is {employee_performance}.")

Ellen's performance is 300.0.


###Calculate the performance of each employee
Now you need to calculate the performance score of each employee and add these scores to a list.

📌 Create an empty list "performance_scores" to hold the scores.

📌 Use a for loop to convert the scores into integer type data and append it to the list "sperformance_scores".

In [185]:
#Calculate the performance of each employee and add into performance_array.
performance_array = np.array([],dtype=int)
for name in names_list:
    performance_array = np.append(performance_array, int(calculate_performance(data, names_list, name)))
print(f"All the performances: {performance_array}")

All the performances: [  64   36  576 1040   25  192  166  300   60   26   75]


###Add the scores to the "data" array

Next, you need to add the scores to your "data" array and print the result.

📌 Use the .concatenate() method to add the "performance_scores" list to the "data" array. 

In [187]:
#Print the resulting array
data = data.reshape(1,44)
data = np.append(data, performance_array)
data = data.reshape(5,11)
print(f"All arrays concatenated. Result: {data}")

All arrays concatenated. Result: [[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]
 [   64    36   576  1040    25   192   166   300    60    26    75]]


###Find out the best and worst performing employees

Finally, you need to determine the best and worst performing employees.

📌 Use the .argmax() and .argmin() methods to find the index of the best and worst performing employees.

In [188]:
#Use .argmax() and .argmin() methods to determine the best and worst performing employees
index_worst_performance = np.argmin(data[4])
index_best_performance = np.argmax(data[4])

#Print out the results
print(f"Worst performer is {names_list[index_worst_performance]}")
print(f"Best performer is {names_list[index_best_performance]}")

Worst performer is Sue
Best performer is Celine
